source 'https://rubygems.org'


gem 'rails', '4.2.5'
gem 'puma'
gem 'rails-api'

gem 'spring', :group => :development

gem 'rack-cors', :require => 'rack/cors'
gem 'pg'
gem 'active_model_serializers', git: 'git://github.com/rails-api/active_model_serializers.git', branch: 'master'
gem 'devise_token_auth'
gem 'omniauth'
gem 'foreman'
gem 'guard-rails'
gem 'responders'
group :test do
  gem 'database_cleaner'
  gem 'guard-rspec'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem "shoulda-matchers"
end